# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/snandaku/repos/work/new-media/qmedia

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/snandaku/repos/work/new-media/qmedia

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/snandaku/repos/work/new-media/qmedia/CMakeFiles /Users/snandaku/repos/work/new-media/qmedia/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/snandaku/repos/work/new-media/qmedia/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /Users/snandaku/repos/work/new-media/qmedia/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named neoMedia

# Build rule for target.
neoMedia: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 neoMedia
.PHONY : neoMedia

# fast build rule for target.
neoMedia/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/build
.PHONY : neoMedia/fast

#=============================================================================
# Target rules for targets named sframe

# Build rule for target.
sframe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sframe
.PHONY : sframe

# fast build rule for target.
sframe/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sframe-build/CMakeFiles/sframe.dir/build.make _deps/sframe-build/CMakeFiles/sframe.dir/build
.PHONY : sframe/fast

#=============================================================================
# Target rules for targets named gsl-extern

# Build rule for target.
gsl-extern: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gsl-extern
.PHONY : gsl-extern

# fast build rule for target.
gsl-extern/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sframe-build/CMakeFiles/gsl-extern.dir/build.make _deps/sframe-build/CMakeFiles/gsl-extern.dir/build
.PHONY : gsl-extern/fast

#=============================================================================
# Target rules for targets named media_api

# Build rule for target.
media_api: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 media_api
.PHONY : media_api

# fast build rule for target.
media_api/fast:
	$(MAKE) $(MAKESILENT) -f proto/CMakeFiles/media_api.dir/build.make proto/CMakeFiles/media_api.dir/build
.PHONY : media_api/fast

#=============================================================================
# Target rules for targets named neo_media_client

# Build rule for target.
neo_media_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 neo_media_client
.PHONY : neo_media_client

# fast build rule for target.
neo_media_client/fast:
	$(MAKE) $(MAKESILENT) -f src/extern/CMakeFiles/neo_media_client.dir/build.make src/extern/CMakeFiles/neo_media_client.dir/build
.PHONY : neo_media_client/fast

#=============================================================================
# Target rules for targets named sound

# Build rule for target.
sound: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sound
.PHONY : sound

# fast build rule for target.
sound/fast:
	$(MAKE) $(MAKESILENT) -f cmd/CMakeFiles/sound.dir/build.make cmd/CMakeFiles/sound.dir/build
.PHONY : sound/fast

#=============================================================================
# Target rules for targets named forty

# Build rule for target.
forty: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 forty
.PHONY : forty

# fast build rule for target.
forty/fast:
	$(MAKE) $(MAKESILENT) -f cmd/CMakeFiles/forty.dir/build.make cmd/CMakeFiles/forty.dir/build
.PHONY : forty/fast

#=============================================================================
# Target rules for targets named neoMedia_test

# Build rule for target.
neoMedia_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 neoMedia_test
.PHONY : neoMedia_test

# fast build rule for target.
neoMedia_test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/neoMedia_test.dir/build.make test/CMakeFiles/neoMedia_test.dir/build
.PHONY : neoMedia_test/fast

src/audio_encoder.o: src/audio_encoder.cc.o

.PHONY : src/audio_encoder.o

# target to build an object file
src/audio_encoder.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/audio_encoder.cc.o
.PHONY : src/audio_encoder.cc.o

src/audio_encoder.i: src/audio_encoder.cc.i

.PHONY : src/audio_encoder.i

# target to preprocess a source file
src/audio_encoder.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/audio_encoder.cc.i
.PHONY : src/audio_encoder.cc.i

src/audio_encoder.s: src/audio_encoder.cc.s

.PHONY : src/audio_encoder.s

# target to generate assembly for a file
src/audio_encoder.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/audio_encoder.cc.s
.PHONY : src/audio_encoder.cc.s

src/extern/neo_media_client.o: src/extern/neo_media_client.cc.o

.PHONY : src/extern/neo_media_client.o

# target to build an object file
src/extern/neo_media_client.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/extern/neo_media_client.cc.o
.PHONY : src/extern/neo_media_client.cc.o

src/extern/neo_media_client.i: src/extern/neo_media_client.cc.i

.PHONY : src/extern/neo_media_client.i

# target to preprocess a source file
src/extern/neo_media_client.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/extern/neo_media_client.cc.i
.PHONY : src/extern/neo_media_client.cc.i

src/extern/neo_media_client.s: src/extern/neo_media_client.cc.s

.PHONY : src/extern/neo_media_client.s

# target to generate assembly for a file
src/extern/neo_media_client.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/extern/neo_media_client.cc.s
.PHONY : src/extern/neo_media_client.cc.s

src/full_Fill.o: src/full_Fill.cc.o

.PHONY : src/full_Fill.o

# target to build an object file
src/full_Fill.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/full_Fill.cc.o
.PHONY : src/full_Fill.cc.o

src/full_Fill.i: src/full_Fill.cc.i

.PHONY : src/full_Fill.i

# target to preprocess a source file
src/full_Fill.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/full_Fill.cc.i
.PHONY : src/full_Fill.cc.i

src/full_Fill.s: src/full_Fill.cc.s

.PHONY : src/full_Fill.s

# target to generate assembly for a file
src/full_Fill.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/full_Fill.cc.s
.PHONY : src/full_Fill.cc.s

src/h264_decoder.o: src/h264_decoder.cc.o

.PHONY : src/h264_decoder.o

# target to build an object file
src/h264_decoder.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/h264_decoder.cc.o
.PHONY : src/h264_decoder.cc.o

src/h264_decoder.i: src/h264_decoder.cc.i

.PHONY : src/h264_decoder.i

# target to preprocess a source file
src/h264_decoder.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/h264_decoder.cc.i
.PHONY : src/h264_decoder.cc.i

src/h264_decoder.s: src/h264_decoder.cc.s

.PHONY : src/h264_decoder.s

# target to generate assembly for a file
src/h264_decoder.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/h264_decoder.cc.s
.PHONY : src/h264_decoder.cc.s

src/h264_encoder.o: src/h264_encoder.cc.o

.PHONY : src/h264_encoder.o

# target to build an object file
src/h264_encoder.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/h264_encoder.cc.o
.PHONY : src/h264_encoder.cc.o

src/h264_encoder.i: src/h264_encoder.cc.i

.PHONY : src/h264_encoder.i

# target to preprocess a source file
src/h264_encoder.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/h264_encoder.cc.i
.PHONY : src/h264_encoder.cc.i

src/h264_encoder.s: src/h264_encoder.cc.s

.PHONY : src/h264_encoder.s

# target to generate assembly for a file
src/h264_encoder.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/h264_encoder.cc.s
.PHONY : src/h264_encoder.cc.s

src/jitter.o: src/jitter.cc.o

.PHONY : src/jitter.o

# target to build an object file
src/jitter.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/jitter.cc.o
.PHONY : src/jitter.cc.o

src/jitter.i: src/jitter.cc.i

.PHONY : src/jitter.i

# target to preprocess a source file
src/jitter.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/jitter.cc.i
.PHONY : src/jitter.cc.i

src/jitter.s: src/jitter.cc.s

.PHONY : src/jitter.s

# target to generate assembly for a file
src/jitter.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/jitter.cc.s
.PHONY : src/jitter.cc.s

src/jitter_queues.o: src/jitter_queues.cc.o

.PHONY : src/jitter_queues.o

# target to build an object file
src/jitter_queues.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/jitter_queues.cc.o
.PHONY : src/jitter_queues.cc.o

src/jitter_queues.i: src/jitter_queues.cc.i

.PHONY : src/jitter_queues.i

# target to preprocess a source file
src/jitter_queues.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/jitter_queues.cc.i
.PHONY : src/jitter_queues.cc.i

src/jitter_queues.s: src/jitter_queues.cc.s

.PHONY : src/jitter_queues.s

# target to generate assembly for a file
src/jitter_queues.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/jitter_queues.cc.s
.PHONY : src/jitter_queues.cc.s

src/jitter_silence.o: src/jitter_silence.cc.o

.PHONY : src/jitter_silence.o

# target to build an object file
src/jitter_silence.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/jitter_silence.cc.o
.PHONY : src/jitter_silence.cc.o

src/jitter_silence.i: src/jitter_silence.cc.i

.PHONY : src/jitter_silence.i

# target to preprocess a source file
src/jitter_silence.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/jitter_silence.cc.i
.PHONY : src/jitter_silence.cc.i

src/jitter_silence.s: src/jitter_silence.cc.s

.PHONY : src/jitter_silence.s

# target to generate assembly for a file
src/jitter_silence.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/jitter_silence.cc.s
.PHONY : src/jitter_silence.cc.s

src/logger.o: src/logger.cc.o

.PHONY : src/logger.o

# target to build an object file
src/logger.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/logger.cc.o
.PHONY : src/logger.cc.o

src/logger.i: src/logger.cc.i

.PHONY : src/logger.i

# target to preprocess a source file
src/logger.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/logger.cc.i
.PHONY : src/logger.cc.i

src/logger.s: src/logger.cc.s

.PHONY : src/logger.s

# target to generate assembly for a file
src/logger.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/logger.cc.s
.PHONY : src/logger.cc.s

src/loopback-jitter.o: src/loopback-jitter.cc.o

.PHONY : src/loopback-jitter.o

# target to build an object file
src/loopback-jitter.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/loopback-jitter.cc.o
.PHONY : src/loopback-jitter.cc.o

src/loopback-jitter.i: src/loopback-jitter.cc.i

.PHONY : src/loopback-jitter.i

# target to preprocess a source file
src/loopback-jitter.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/loopback-jitter.cc.i
.PHONY : src/loopback-jitter.cc.i

src/loopback-jitter.s: src/loopback-jitter.cc.s

.PHONY : src/loopback-jitter.s

# target to generate assembly for a file
src/loopback-jitter.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/loopback-jitter.cc.s
.PHONY : src/loopback-jitter.cc.s

src/metrics.o: src/metrics.cc.o

.PHONY : src/metrics.o

# target to build an object file
src/metrics.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/metrics.cc.o
.PHONY : src/metrics.cc.o

src/metrics.i: src/metrics.cc.i

.PHONY : src/metrics.i

# target to preprocess a source file
src/metrics.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/metrics.cc.i
.PHONY : src/metrics.cc.i

src/metrics.s: src/metrics.cc.s

.PHONY : src/metrics.s

# target to generate assembly for a file
src/metrics.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/metrics.cc.s
.PHONY : src/metrics.cc.s

src/modulus_deque.o: src/modulus_deque.cc.o

.PHONY : src/modulus_deque.o

# target to build an object file
src/modulus_deque.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/modulus_deque.cc.o
.PHONY : src/modulus_deque.cc.o

src/modulus_deque.i: src/modulus_deque.cc.i

.PHONY : src/modulus_deque.i

# target to preprocess a source file
src/modulus_deque.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/modulus_deque.cc.i
.PHONY : src/modulus_deque.cc.i

src/modulus_deque.s: src/modulus_deque.cc.s

.PHONY : src/modulus_deque.s

# target to generate assembly for a file
src/modulus_deque.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/modulus_deque.cc.s
.PHONY : src/modulus_deque.cc.s

src/neo.o: src/neo.cc.o

.PHONY : src/neo.o

# target to build an object file
src/neo.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/neo.cc.o
.PHONY : src/neo.cc.o

src/neo.i: src/neo.cc.i

.PHONY : src/neo.i

# target to preprocess a source file
src/neo.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/neo.cc.i
.PHONY : src/neo.cc.i

src/neo.s: src/neo.cc.s

.PHONY : src/neo.s

# target to generate assembly for a file
src/neo.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/neo.cc.s
.PHONY : src/neo.cc.s

src/netTransportQuic.o: src/netTransportQuic.cc.o

.PHONY : src/netTransportQuic.o

# target to build an object file
src/netTransportQuic.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/netTransportQuic.cc.o
.PHONY : src/netTransportQuic.cc.o

src/netTransportQuic.i: src/netTransportQuic.cc.i

.PHONY : src/netTransportQuic.i

# target to preprocess a source file
src/netTransportQuic.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/netTransportQuic.cc.i
.PHONY : src/netTransportQuic.cc.i

src/netTransportQuic.s: src/netTransportQuic.cc.s

.PHONY : src/netTransportQuic.s

# target to generate assembly for a file
src/netTransportQuic.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/netTransportQuic.cc.s
.PHONY : src/netTransportQuic.cc.s

src/netTransportQuicR.o: src/netTransportQuicR.cc.o

.PHONY : src/netTransportQuicR.o

# target to build an object file
src/netTransportQuicR.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/netTransportQuicR.cc.o
.PHONY : src/netTransportQuicR.cc.o

src/netTransportQuicR.i: src/netTransportQuicR.cc.i

.PHONY : src/netTransportQuicR.i

# target to preprocess a source file
src/netTransportQuicR.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/netTransportQuicR.cc.i
.PHONY : src/netTransportQuicR.cc.i

src/netTransportQuicR.s: src/netTransportQuicR.cc.s

.PHONY : src/netTransportQuicR.s

# target to generate assembly for a file
src/netTransportQuicR.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/netTransportQuicR.cc.s
.PHONY : src/netTransportQuicR.cc.s

src/netTransportUDP.o: src/netTransportUDP.cc.o

.PHONY : src/netTransportUDP.o

# target to build an object file
src/netTransportUDP.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/netTransportUDP.cc.o
.PHONY : src/netTransportUDP.cc.o

src/netTransportUDP.i: src/netTransportUDP.cc.i

.PHONY : src/netTransportUDP.i

# target to preprocess a source file
src/netTransportUDP.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/netTransportUDP.cc.i
.PHONY : src/netTransportUDP.cc.i

src/netTransportUDP.s: src/netTransportUDP.cc.s

.PHONY : src/netTransportUDP.s

# target to generate assembly for a file
src/netTransportUDP.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/netTransportUDP.cc.s
.PHONY : src/netTransportUDP.cc.s

src/opus_assembler.o: src/opus_assembler.cc.o

.PHONY : src/opus_assembler.o

# target to build an object file
src/opus_assembler.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/opus_assembler.cc.o
.PHONY : src/opus_assembler.cc.o

src/opus_assembler.i: src/opus_assembler.cc.i

.PHONY : src/opus_assembler.i

# target to preprocess a source file
src/opus_assembler.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/opus_assembler.cc.i
.PHONY : src/opus_assembler.cc.i

src/opus_assembler.s: src/opus_assembler.cc.s

.PHONY : src/opus_assembler.s

# target to generate assembly for a file
src/opus_assembler.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/opus_assembler.cc.s
.PHONY : src/opus_assembler.cc.s

src/packet.o: src/packet.cc.o

.PHONY : src/packet.o

# target to build an object file
src/packet.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/packet.cc.o
.PHONY : src/packet.cc.o

src/packet.i: src/packet.cc.i

.PHONY : src/packet.i

# target to preprocess a source file
src/packet.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/packet.cc.i
.PHONY : src/packet.cc.i

src/packet.s: src/packet.cc.s

.PHONY : src/packet.s

# target to generate assembly for a file
src/packet.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/packet.cc.s
.PHONY : src/packet.cc.s

src/playout_leakybucket.o: src/playout_leakybucket.cc.o

.PHONY : src/playout_leakybucket.o

# target to build an object file
src/playout_leakybucket.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/playout_leakybucket.cc.o
.PHONY : src/playout_leakybucket.cc.o

src/playout_leakybucket.i: src/playout_leakybucket.cc.i

.PHONY : src/playout_leakybucket.i

# target to preprocess a source file
src/playout_leakybucket.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/playout_leakybucket.cc.i
.PHONY : src/playout_leakybucket.cc.i

src/playout_leakybucket.s: src/playout_leakybucket.cc.s

.PHONY : src/playout_leakybucket.s

# target to generate assembly for a file
src/playout_leakybucket.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/playout_leakybucket.cc.s
.PHONY : src/playout_leakybucket.cc.s

src/playout_sync.o: src/playout_sync.cc.o

.PHONY : src/playout_sync.o

# target to build an object file
src/playout_sync.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/playout_sync.cc.o
.PHONY : src/playout_sync.cc.o

src/playout_sync.i: src/playout_sync.cc.i

.PHONY : src/playout_sync.i

# target to preprocess a source file
src/playout_sync.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/playout_sync.cc.i
.PHONY : src/playout_sync.cc.i

src/playout_sync.s: src/playout_sync.cc.s

.PHONY : src/playout_sync.s

# target to generate assembly for a file
src/playout_sync.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/playout_sync.cc.s
.PHONY : src/playout_sync.cc.s

src/playout_tools.o: src/playout_tools.cc.o

.PHONY : src/playout_tools.o

# target to build an object file
src/playout_tools.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/playout_tools.cc.o
.PHONY : src/playout_tools.cc.o

src/playout_tools.i: src/playout_tools.cc.i

.PHONY : src/playout_tools.i

# target to preprocess a source file
src/playout_tools.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/playout_tools.cc.i
.PHONY : src/playout_tools.cc.i

src/playout_tools.s: src/playout_tools.cc.s

.PHONY : src/playout_tools.s

# target to generate assembly for a file
src/playout_tools.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/playout_tools.cc.s
.PHONY : src/playout_tools.cc.s

src/resampler.o: src/resampler.cc.o

.PHONY : src/resampler.o

# target to build an object file
src/resampler.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/resampler.cc.o
.PHONY : src/resampler.cc.o

src/resampler.i: src/resampler.cc.i

.PHONY : src/resampler.i

# target to preprocess a source file
src/resampler.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/resampler.cc.i
.PHONY : src/resampler.cc.i

src/resampler.s: src/resampler.cc.s

.PHONY : src/resampler.s

# target to generate assembly for a file
src/resampler.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/resampler.cc.s
.PHONY : src/resampler.cc.s

src/rtx_manager.o: src/rtx_manager.cc.o

.PHONY : src/rtx_manager.o

# target to build an object file
src/rtx_manager.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/rtx_manager.cc.o
.PHONY : src/rtx_manager.cc.o

src/rtx_manager.i: src/rtx_manager.cc.i

.PHONY : src/rtx_manager.i

# target to preprocess a source file
src/rtx_manager.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/rtx_manager.cc.i
.PHONY : src/rtx_manager.cc.i

src/rtx_manager.s: src/rtx_manager.cc.s

.PHONY : src/rtx_manager.s

# target to generate assembly for a file
src/rtx_manager.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/rtx_manager.cc.s
.PHONY : src/rtx_manager.cc.s

src/simple_packetize.o: src/simple_packetize.cc.o

.PHONY : src/simple_packetize.o

# target to build an object file
src/simple_packetize.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/simple_packetize.cc.o
.PHONY : src/simple_packetize.cc.o

src/simple_packetize.i: src/simple_packetize.cc.i

.PHONY : src/simple_packetize.i

# target to preprocess a source file
src/simple_packetize.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/simple_packetize.cc.i
.PHONY : src/simple_packetize.cc.i

src/simple_packetize.s: src/simple_packetize.cc.s

.PHONY : src/simple_packetize.s

# target to generate assembly for a file
src/simple_packetize.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/simple_packetize.cc.s
.PHONY : src/simple_packetize.cc.s

src/simple_video_assembler.o: src/simple_video_assembler.cc.o

.PHONY : src/simple_video_assembler.o

# target to build an object file
src/simple_video_assembler.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/simple_video_assembler.cc.o
.PHONY : src/simple_video_assembler.cc.o

src/simple_video_assembler.i: src/simple_video_assembler.cc.i

.PHONY : src/simple_video_assembler.i

# target to preprocess a source file
src/simple_video_assembler.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/simple_video_assembler.cc.i
.PHONY : src/simple_video_assembler.cc.i

src/simple_video_assembler.s: src/simple_video_assembler.cc.s

.PHONY : src/simple_video_assembler.s

# target to generate assembly for a file
src/simple_video_assembler.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/simple_video_assembler.cc.s
.PHONY : src/simple_video_assembler.cc.s

src/transport_manager.o: src/transport_manager.cc.o

.PHONY : src/transport_manager.o

# target to build an object file
src/transport_manager.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/transport_manager.cc.o
.PHONY : src/transport_manager.cc.o

src/transport_manager.i: src/transport_manager.cc.i

.PHONY : src/transport_manager.i

# target to preprocess a source file
src/transport_manager.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/transport_manager.cc.i
.PHONY : src/transport_manager.cc.i

src/transport_manager.s: src/transport_manager.cc.s

.PHONY : src/transport_manager.s

# target to generate assembly for a file
src/transport_manager.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neoMedia.dir/build.make CMakeFiles/neoMedia.dir/src/transport_manager.cc.s
.PHONY : src/transport_manager.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gsl-extern"
	@echo "... forty"
	@echo "... media_api"
	@echo "... neoMedia"
	@echo "... neoMedia_test"
	@echo "... neo_media_client"
	@echo "... sframe"
	@echo "... sound"
	@echo "... src/audio_encoder.o"
	@echo "... src/audio_encoder.i"
	@echo "... src/audio_encoder.s"
	@echo "... src/extern/neo_media_client.o"
	@echo "... src/extern/neo_media_client.i"
	@echo "... src/extern/neo_media_client.s"
	@echo "... src/full_Fill.o"
	@echo "... src/full_Fill.i"
	@echo "... src/full_Fill.s"
	@echo "... src/h264_decoder.o"
	@echo "... src/h264_decoder.i"
	@echo "... src/h264_decoder.s"
	@echo "... src/h264_encoder.o"
	@echo "... src/h264_encoder.i"
	@echo "... src/h264_encoder.s"
	@echo "... src/jitter.o"
	@echo "... src/jitter.i"
	@echo "... src/jitter.s"
	@echo "... src/jitter_queues.o"
	@echo "... src/jitter_queues.i"
	@echo "... src/jitter_queues.s"
	@echo "... src/jitter_silence.o"
	@echo "... src/jitter_silence.i"
	@echo "... src/jitter_silence.s"
	@echo "... src/logger.o"
	@echo "... src/logger.i"
	@echo "... src/logger.s"
	@echo "... src/loopback-jitter.o"
	@echo "... src/loopback-jitter.i"
	@echo "... src/loopback-jitter.s"
	@echo "... src/metrics.o"
	@echo "... src/metrics.i"
	@echo "... src/metrics.s"
	@echo "... src/modulus_deque.o"
	@echo "... src/modulus_deque.i"
	@echo "... src/modulus_deque.s"
	@echo "... src/neo.o"
	@echo "... src/neo.i"
	@echo "... src/neo.s"
	@echo "... src/netTransportQuic.o"
	@echo "... src/netTransportQuic.i"
	@echo "... src/netTransportQuic.s"
	@echo "... src/netTransportQuicR.o"
	@echo "... src/netTransportQuicR.i"
	@echo "... src/netTransportQuicR.s"
	@echo "... src/netTransportUDP.o"
	@echo "... src/netTransportUDP.i"
	@echo "... src/netTransportUDP.s"
	@echo "... src/opus_assembler.o"
	@echo "... src/opus_assembler.i"
	@echo "... src/opus_assembler.s"
	@echo "... src/packet.o"
	@echo "... src/packet.i"
	@echo "... src/packet.s"
	@echo "... src/playout_leakybucket.o"
	@echo "... src/playout_leakybucket.i"
	@echo "... src/playout_leakybucket.s"
	@echo "... src/playout_sync.o"
	@echo "... src/playout_sync.i"
	@echo "... src/playout_sync.s"
	@echo "... src/playout_tools.o"
	@echo "... src/playout_tools.i"
	@echo "... src/playout_tools.s"
	@echo "... src/resampler.o"
	@echo "... src/resampler.i"
	@echo "... src/resampler.s"
	@echo "... src/rtx_manager.o"
	@echo "... src/rtx_manager.i"
	@echo "... src/rtx_manager.s"
	@echo "... src/simple_packetize.o"
	@echo "... src/simple_packetize.i"
	@echo "... src/simple_packetize.s"
	@echo "... src/simple_video_assembler.o"
	@echo "... src/simple_video_assembler.i"
	@echo "... src/simple_video_assembler.s"
	@echo "... src/transport_manager.o"
	@echo "... src/transport_manager.i"
	@echo "... src/transport_manager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /Users/snandaku/repos/work/new-media/qmedia/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

